spring:
  application:
    name: movie-catalog-service
#  cloud:
#    config:
#      uri: 'http://127.0.0.1:8888'

server:
  port: 8081

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka

management.endpoints.web.exposure.include: hystrix.stream

spring.config.import: 'configserver:http://localhost:8888'