spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      enabled: true
      server.native.searchLocations: classpath:configrepo/
#     server.native.git.uri: file:///C:/Users/akashsnc/Desktop/configGitRepo

#management.endpoints.web.exposure.include: '*'
